### ISSUE TITLE
Uncaught SyntaxError: Unexpected end of input

### ISSUE THREAD

**Issue by scott-knight** [matugm/ruby-navigator#1]
1. Clicked toolbar on Packages > ruby-navigator > toggle

Im running ruby 2.2.2 and rails 3.2

**Atom Version**: 1.0.7
**System**: Mac OS X 10.10.4
**Thrown From**: [ruby-navigator](https://github.com/matugm/ruby-navigator) package, v0.5.0
### Stack Trace

Uncaught SyntaxError: Unexpected end of input

```
At file:///Applications/Atom.app/Contents/Resources/app.asar/static/index.html#%7B%22locationsToOpen%22%3A%5B%7B%22pathToOpen%22%3A%22%2FUsers%2Fsknight%2Frails.projects%2Fpinsightmedia%2Fonelouder_ads.portal_engine%22%7D%5D%2C%22bootstrapScript%22%3A%22%2FApplications%2FAtom.app%2FContents%2FResources%2Fapp.asar%2Fsrc%2Fwindow-bootstrap.js%22%2C%22resourcePath%22%3A%22%2FApplications%2FAtom.app%2FContents%2FResources%2Fapp.asar%22%2C%22devMode%22%3Afalse%2C%22safeMode%22%3Afalse%2C%22profileStartup%22%3Afalse%2C%22appVersion%22%3A%221.0.7%22%2C%22initialPaths%22%3A%5B%22%2FUsers%2Fsknight%2Frails.projects%2Fpinsightmedia%2Fonelouder_ads.portal_engine%22%5D%7D:0

SyntaxError: Unexpected end of input
  at Object.parse (native)
  at RubyNavigatorView.module.exports.RubyNavigatorView.load_data (/Users/sknight/.atom/packages/ruby-navigator/lib/ruby-navigator-view.coffee:33:21)
  at Object.module.exports.RubyNavigator.toggle (/Users/sknight/.atom/packages/ruby-navigator/lib/ruby-navigator.coffee:33:26)
  at atom-workspace.subscriptions.add.atom.commands.add.ruby-navigator:toggle (/Users/sknight/.atom/packages/ruby-navigator/lib/ruby-navigator.coffee:17:89)
  at CommandRegistry.module.exports.CommandRegistry.handleCommandEvent (/Applications/Atom.app/Contents/Resources/app.asar/src/command-registry.js:241:29)
  at CommandRegistry.handleCommandEvent (/Applications/Atom.app/Contents/Resources/app.asar/src/command-registry.js:3:61)
  at CommandRegistry.module.exports.CommandRegistry.dispatch (/Applications/Atom.app/Contents/Resources/app.asar/src/command-registry.js:156:19)
  at EventEmitter.<anonymous> (/Applications/Atom.app/Contents/Resources/app.asar/src/window-event-handler.js:70:30)
  at emitOne (events.js:77:13)
  at EventEmitter.emit (events.js:166:7)

```
### Commands

```
     -9:20.2.0 core:copy (atom-text-editor.editor.is-focused)
  2x -0:03.3.0 ruby-navigator:toggle (atom-text-editor.editor.is-focused)
```
### Config

``` json
{
  "core": {
    "themes": [
      "one-dark-ui",
      "railscasts-prime-syntax"
    ]
  }
}
```
### Installed Packages

``` coffee
# User
atom-beautify, v0.28.11
autocomplete-ruby, v0.1.0
color-picker, v2.0.11
html2haml, v0.10.0
language-haml, v0.21.0
language-slim, v0.5.0
minimap, v4.12.3
pigments, v0.11.0
railscasts-prime-syntax, v1.0.1
ruby-block, v0.3.5
ruby-navigator, v0.5.0
ruby-slim, v0.2.0
trailing-spaces, v0.3.2

# Dev
No dev packages
```

**Comment by matugm** [comment]
Hello,
do you have a `class-index.json` file on the root of your project? If so could you please share the contents of it so I can reproduce the issue?

Thank you.

**Comment by scott-knight** [comment]
Sorry, I dont have that file in the root of my app. I recently downloaded Atom to try it out. I installed and ran the ruby-navigator plugin and the result was what you see in the 'Uncaught SyntaxError: Unexpected end of input' post - it automatically generated.

**Comment by matugm** [comment]
You need to generate that file, that's how the plugin knows what classes you have (this is explained in the plugin description).

To do that you will need to install the 'class-indexer' gem and run the 'indexer > class-index.json' command. The file must be on the root of your project directory. Note that you need to that before toggling the plugin on.

**Comment by scott-knight** [comment]
Good to know. Thank you
