### ISSUE TITLE
Uncaught SyntaxError: Unexpected token =

### ISSUE THREAD

**Issue by wrecklass** [matugm/ruby-navigator#2]
[Enter steps to reproduce below:]
1. create class-index.json using class_indexer as expected.
2. Use ruby-navigator package with the ruby file opened.

**Atom Version**: 1.0.7
**System**: Mac OS X 10.10.4
**Thrown From**: [ruby-navigator](https://github.com/matugm/ruby-navigator) package, v0.5.0
### Stack Trace

Uncaught SyntaxError: Unexpected token =

```
At file:///Users/smartin/Applications/Atom.app/Contents/Resources/app.asar/static/index.html#%7B%22locationsToOpen%22%3A%5B%7B%22pathToOpen%22%3A%22%2FUsers%2Fsmartin%2Fsrc%2Fsensu-community-plugins%2Fplugins%2Fmonit%2Fmonit-email.rb%22%7D%5D%2C%22bootstrapScript%22%3A%22%2FUsers%2Fsmartin%2FApplications%2FAtom.app%2FContents%2FResources%2Fapp.asar%2Fsrc%2Fwindow-bootstrap.js%22%2C%22resourcePath%22%3A%22%2FUsers%2Fsmartin%2FApplications%2FAtom.app%2FContents%2FResources%2Fapp.asar%22%2C%22devMode%22%3Afalse%2C%22safeMode%22%3Afalse%2C%22profileStartup%22%3Afalse%2C%22appVersion%22%3A%221.0.7%22%2C%22shellLoadTime%22%3A452%2C%22initialPaths%22%3A%5B%22%2FUsers%2Fsmartin%2Fsrc%2Fsensu-community-plugins%2Fplugins%2Fmonit%22%5D%7D:1

SyntaxError: Unexpected token =
  at Object.parse (native)
  at RubyNavigatorView.module.exports.RubyNavigatorView.load_data (/Users/smartin/.atom/packages/ruby-navigator/lib/ruby-navigator-view.coffee:33:21)
  at Object.module.exports.RubyNavigator.toggle (/Users/smartin/.atom/packages/ruby-navigator/lib/ruby-navigator.coffee:33:26)
  at atom-workspace.subscriptions.add.atom.commands.add.ruby-navigator:toggle (/Users/smartin/.atom/packages/ruby-navigator/lib/ruby-navigator.coffee:17:89)
  at CommandRegistry.module.exports.CommandRegistry.handleCommandEvent (/Users/smartin/Applications/Atom.app/Contents/Resources/app.asar/src/command-registry.js:241:29)
  at /Users/smartin/Applications/Atom.app/Contents/Resources/app.asar/src/command-registry.js:3:61
  at KeymapManager.module.exports.KeymapManager.dispatchCommandEvent (/Users/smartin/Applications/Atom.app/Contents/Resources/app.asar/node_modules/atom-keymap/lib/keymap-manager.js:524:16)
  at KeymapManager.module.exports.KeymapManager.handleKeyboardEvent (/Users/smartin/Applications/Atom.app/Contents/Resources/app.asar/node_modules/atom-keymap/lib/keymap-manager.js:347:22)
  at HTMLDocument.module.exports.WindowEventHandler.onKeydown (/Users/smartin/Applications/Atom.app/Contents/Resources/app.asar/src/window-event-handler.js:177:20)

```
### Commands

```
```
### Config

``` json
{
  "core": {
    "themes": [
      "atom-dark-ui",
      "monokai"
    ]
  }
}
```
### Installed Packages

``` coffee
# User
autocomplete-ruby, v0.1.0
git-diff-details, v0.20.0
monokai, v0.18.0
ruby-navigator, v0.5.0
tree-view-git-status, v0.1.2
vim-mode, v0.58.0
vim-surround, v0.8.0

# Dev
No dev packages
```

**Comment by matugm** [comment]
Thanks for the report :)

It seems like the plugin is trying to read a malformed `class-index.json` file. Could you please paste the contents of your `class-index.json` file?
