### ISSUE TITLE
Uncaught SyntaxError: Unexpected end of JSON input

### ISSUE THREAD

**Issue by shivabhusal** [matugm/ruby-navigator#5]
[Steps to reproduce:]

1. I installed the gem `class_indexer`
2. Installed the package `ruby-navigator`
3. Then pressed `Ctrl + Alt + o`

**Atom**: 1.17.1 x64
**Electron**: 1.3.15
**OS**: Ubuntu 17.04
**Thrown From**: [ruby-navigator](https://github.com/matugm/ruby-navigator) package 0.5.0

### Stack Trace

Uncaught SyntaxError: Unexpected end of JSON input

```
At file:///usr/share/atom/resources/app/static/index.html:1

SyntaxError: Unexpected end of JSON input
    at Object.parse (native)
    at RubyNavigatorView.module.exports.RubyNavigatorView.load_data (/packages/ruby-navigator/lib/ruby-navigator-view.coffee:33:21)
    at Object.toggle (/packages/ruby-navigator/lib/ruby-navigator.coffee:33:26)
    at /packages/ruby-navigator/lib/ruby-navigator.coffee:17:89)
    at CommandRegistry.module.exports.CommandRegistry.handleCommandEvent (/usr/share/atom/resources/app/src/command-registry.js:265:1)
    at /usr/share/atom/resources/app/src/command-registry.js:3:1
    at KeymapManager.module.exports.KeymapManager.dispatchCommandEvent (/usr/share/atom/resources/app/node_modules/atom-keymap/lib/keymap-manager.js:610:1)
    at KeymapManager.module.exports.KeymapManager.handleKeyboardEvent (/usr/share/atom/resources/app/node_modules/atom-keymap/lib/keymap-manager.js:401:1)
    at WindowEventHandler.module.exports.WindowEventHandler.handleDocumentKeyEvent (/usr/share/atom/resources/app/src/window-event-handler.js:100:1)
    at HTMLDocument.<anonymous> (/usr/share/atom/resources/app/src/window-event-handler.js:3:1)
```

### Commands

```
```

### Non-Core Packages

```
autocomplete-ruby 0.2.8 
goto-definition 1.3.3 
ruby-navigator 0.5.0 
```

**Comment by matugm** [comment]
Hi @shivabhusal,
thanks for your report!

Right now I'm not working on this Atom package, but feel free to submit a PR if you like. It seems like the problem is related to the JSON file generated by `class_indexer`.
